name: Docker Build and Push Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image 0.14.1
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/kelseymok/terraform-workspace:0.14.1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            TERRAFORM_VERSION=0.14.1
      - name: Build container image 1.1.3
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/kelseymok/terraform-workspace:1.1.3
            ghcr.io/kelseymok/terraform-workspace:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            TERRAFORM_VERSION=1.1.3